apiVersion: apps/v1
kind: Deployment
metadata:
  name: testes-mongodb
spec:
  selector:
    matchLabels:
      app: testes-mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: testes-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: MongoDB2022!
          ports:
          - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: testes-mongodb-service
spec:
  selector:
    app: testes-mongodb
  ports:
    - name: mongodb
      port: 27017
      nodePort: 30017
  type: NodePort